[package]
name = "sway-alttab"
description = "alt-tab window switch implementaion for sway"
version = "0.1.0"
authors = [
    "x1b6e6 <ftdabcde@gmail.com>"
]
edition = "2018"

[dependencies]
evdev-rs-tokio = "0.4"
clap = "2.33"
nix = "0.23"

[dependencies.tokio]
version = "1.12.0"
features = [
    "fs",
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
]

[dependencies.swayipc]
git = "https://github.com/jaycefayne/swayipc-rs"
